### PR TITLE
Spanish translation fixed

### PR DESCRIPTION
**Pull request by urizev**

### CODE REVIEW

**Comment by msoultanidis** [comment]
Could you please translate some more strings I just added? Also I just noticed that you wrapped the strings inside double quotes. Please change that as they are not needed.

Thanks for your time!

**Comment by urizev** [comment]
Ok, I'll do it.

**Comment by urizev** [comment]
Fixes and translations done.

**Comment by msoultanidis** [comment]
Merged!

**Comment by urizev** [comment]
@msoultanidis, are you going to notify us if there are new strings to translate or do we have to check the strings regularly?

**Pull request merged**
