### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by RodolfoCandido**
values-pt-rBR/strings.xml based on the latest (July 1, 2021) values/strings.xml

### CODE REVIEW

**Comment by msoultanidis** [comment]
Could you please translate some more strings I just added?

Thanks for your time!

**Comment by RodolfoCandido** [comment]
Sure! How I update this request? I need to open a new pull request with the updated file, or if I update it at my repository it will auto update this?

**Comment by msoultanidis** [comment]
> Sure! How I update this request? I need to open a new pull request with the updated file, or if I update it at my repository it will auto update this?

Just make a commit and push it.

**Comment by RodolfoCandido** [comment]
> > Sure! How I update this request? I need to open a new pull request with the updated file, or if I update it at my repository it will auto update this?
> 
> Just make a commit and push it.

Got it! 

Thank you for the help and for the wonderful app

**Comment by msoultanidis** [comment]
Looks good, merged!

**Pull request merged**
